# Generated by Django 2.2.7 on 2019-12-23 12:23

import articles.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('weiter', models.CharField(max_length=100, verbose_name='Writer')),
                ('published_on', models.DateField(default=django.utils.timezone.now, verbose_name='Published on')),
                ('genre', models.CharField(max_length=50, verbose_name='Genre')),
                ('modified_on', models.DateField(auto_now=True, verbose_name='')),
                ('title_image', models.ImageField(blank=True, null=True, upload_to=articles.models.upload_image, verbose_name='Image')),
            ],
        ),
    ]
