# Generated by Django 2.2.7 on 2020-01-06 11:50

from django.db import migrations, models
import taggit.managers
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='weiter',
        ),
        migrations.AddField(
            model_name='articles',
            name='body',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='articles',
            name='keywords',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='articles',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='articles',
            name='writer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Writer'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='genre',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='modified_on',
            field=models.DateField(auto_now=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='articles',
            name='published_on',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Published on'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Title'),
        ),
    ]
